### PR TITLE
chore: Use PyPI OIDC to publish

### PR DESCRIPTION
**Pull request by edgarrmondragon**
TODO: decide if we want to set up an _environment_ for releases.

For now, I've created a published without an environment.

----
:books: Documentation preview :books:: https://meltano-edk--97.org.readthedocs.build/en/97/

### CODE REVIEW

**Comment by WillDaSilva** [comment]
@edgarrmondragon How much work (both now and ongoing) is it to set up & use an environment for releases? Even if we don't need it, if it isn't much work I'd still support us using an environment for releases since that'll make it easier to e.g. require approval for publishing later.

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon How much work (both now and ongoing) is it to set up & use an environment for releases? Even if we don't need it, if it isn't much work I'd still support us using an environment for releases since that'll make it easier to e.g. require approval for publishing later.

@WillDaSilva It's a really simple process:

1. Recreate the publisher in PyPI to use the `publishing` environment
2. Create the `publishing` environment in this repo with basic settings, e.g. limit to `v*` tags
3. Update this PR to make the job use that environment

It's a bit of click-ops that in total that takes 10 minutes max. Though, I don't have access to all settings in this repo so I can't create the environment (cc @tayloramurphy).

**Comment by WillDaSilva** [comment]
> Though, I don't have access to all settings in this repo so I can't create the environment

@edgarrmondragon I've made you an org owner, so you should now have the required permissions. After this process is done you or I can drop your access level down to member.

**Comment by tayloramurphy** [comment]
@WillDaSilva @edgarrmondragon currently Edgar is Admin on SDK repo - do we want the same on the EDK repo?

**Comment by edgarrmondragon** [comment]
> @WillDaSilva @edgarrmondragon currently Edgar is Admin on SDK repo - do we want the same on the EDK repo?

Yeah, that'd be fine by me 🙂.

**Comment by edgarrmondragon** [comment]
Published successfully: https://pypi.org/project/meltano-edk/0.3.1a1/

**Comment by edgarrmondragon** [comment]
Published successfully: https://pypi.org/project/meltano-edk/0.3.1a1/

**Review by WillDaSilva — APPROVED** [review]

**Pull request merged**
