### PR TITLE
chore: Add gitignore file

### PR DESCRIPTION
**Pull request by menzenski**
Related issue: https://github.com/meltano/edk/issues/41

----
:books: Documentation preview :books:: https://meltano-edk--42.org.readthedocs.build/en/42/

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
Tests are failing, I'm working on a fix in #43

**Comment by edgarrmondragon** [comment]
@menzenski can you merge `main` into your branch? I had to fix our tests.

**Comment by menzenski** [comment]
@edgarrmondragon done!

**Comment by edgarrmondragon** [comment]
Thanks @menzenski!

**Review by edgarrmondragon — APPROVED** [review]

**Pull request merged**
